import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    presets: [
        require('./vendor/wireui/wireui/tailwind.config.js'),
        require("./vendor/power-components/livewire-powergrid/tailwind.config.js"),
    ],
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './config/App/PowerGridThemes/**/*.php',
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./node_modules/tw-elements/dist/js/**/*.js",
        './app/Http/Livewire/**/*Table.php',
        './vendor/power-components/livewire-powergrid/resources/views/**/*.php',
        './vendor/power-components/livewire-powergrid/src/Themes/Tailwind.php',
        "./vendor/wireui/wireui/src/*.php",
        "./vendor/wireui/wireui/src/**/*.php",
        "./vendor/wireui/wireui/ts/**/*.ts",
        "./vendor/wireui/wireui/src/View/**/*.php",
        "./vendor/wireui/wireui/src/WireUi/**/*.php",
        "./vendor/wireui/wireui/src/resources/**/*.blade.php",
        './config/livewire-ui-modal.php',
        './storage/framework/views/*.php',
        './app/Livewire/**/*Table.php',
        './vendor/power-components/livewire-powergrid/resources/views/**/*.php',
        './vendor/power-components/livewire-powergrid/src/Themes/Tailwind.php',
        './vendor/wireui/wireui/src/Components/**/*.blade.php',
        './vendor/wireui/**'
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },
    safelist: [
        {
            pattern: /max-w-(sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl)/,
            variants: ['sm', 'md', 'lg', 'xl', '2xl', 'xl'],
        },
        'bg-pg-primary-100',
        'dark:bg-pg-primary-900',
        'ease-in',
        'duration-150',
        'rounded-full',
        'ring-negative-500',
        'bg-negative-500',
        'hover:bg-negative-600',
        'hover:ring-negative-600',
        'dark:ring-offset-slate-800',
        'dark:bg-negative-700',
        'dark:ring-negative-700',
        'dark:hover:bg-negative-600',
        'dark:hover:ring-negative-600',
        'bg-warning-500',
        'dark:bg-warning-700',
        'hover:bg-warning-600',
        'dark:hover:bg-warning-600',
        'focus:bg-warning-600',
        'focus:ring-warning-600',
        'dark:focus:bg-warning-600',
        'dark:focus:ring-warning-600',
        'py-2',
        'outline-none',
        'inline-flex',
        'justify-center',
        'items-center',
        'group',
        'hover:shadow-sm',
        'focus:ring-offset-background-white',
        'dark:focus:ring-offset-background-dark',
        'transition-all',
        'ease-in-out',
        'duration-200',
        'focus:ring-2',
        'disabled:opacity-80',
        'disabled:cursor-not-allowed',
        'text-white',
        'bg-primary-500',
        'dark:bg-primary-700',
        'hover:text-white',
        'hover:bg-primary-600',
        'dark:hover:bg-primary-600',
        // 'focus:text-white',
        'focus:ring-offset-2',
        'focus:bg-primary-600',
        'focus:ring-primary-600',
        'dark:focus:bg-primary-600',
        'dark:focus:ring-primary-600',
        'rounded-md',
        'gap-x-2',
        'text-sm',
        'px-4',
        'py-2',
        'readonly:border-none',
        'readonly:bg-transparent',
        '!bg-gray-600',
        'bg-gray-600'
    ],
    darkMode: "class",
    plugins: [forms, typography]
};
